[tool.black]
line-length = 100
target-version = ['py36']
force-exclude = '''
/(
  | mlflow/protos
  | tests/protos
)/
'''

[tool.isort]
profile = 'black'
skip_glob = [
  'docs/source/conf.py',
  'mlflow/store/db_migrations/versions/*.py',
  'mlflow/protos/*.py',
  'tests/protos/*.py',
]
line_length = 100
lines_after_imports = 2
force_alphabetical_sort_within_sections = 'True'
force_sort_within_sections = 'True'
