version: 2.1

# TODO: Remove this job once MLflow 3.1.3 is released
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run: ls

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
