name: AI Command Handler

on:
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-command:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/ai')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            .github/scripts/ai/

      - name: Process AI command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/ai/index.js
