name: Automerge

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

  schedule:
    - cron: "*/10 * * * *" # Run every 10 minutes

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Automerge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            const script = require('./.github/workflows/automerge.js');
            const dryRun = '${{ github.event.inputs.dry-run }}' === 'true';
            await script({ github, context, dryRun });
