name: Autoformat
on: [issue_comment, pull_request]

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  # Commenting '/autoformat' on a pull request triggers this workflow.
  # This allows both maintainers and contributors to trigger this workflow.
  parse-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      matched: ${{ steps.parse-comment.outputs.matched }}
    steps:
      - name: Parse comment
        id: parse-comment
        run: |
          # Trim whitespaces and newlines
          trimmed=$(echo "${{ github.event.comment.body }}" | tr -d '[:space:]')
          matched=$([[ "$trimmed" == "/autoformat" ]] && echo "true" || echo "false")
          echo "::set-output name=matched::$matched"
  autoformat:
    runs-on: ubuntu-latest
    # needs: parse-comment
    # if: ${{ needs.parse-comment.outputs.matched == 'true' }}
    steps:
      - uses: actions/github-script@v4
        id: get-pr
        with:
          script: |
            const {
              repo: { owner, repo },
              issue: { number: pull_number },
            } = context;
            const pr = await github.pulls.get({ owner, repo, pull_number });
            return pr.data
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
          # As mentioned in the doc below, if we use `secrets.GITHUB_TOKEN`, a commit cerated by
          # this workflow will not trigger other GitHub Actions workflows:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # To make it work, register a personal access token for the mlflow-automation bot as
          # a secret in the repository and use it.
          # token: ${{ secrets.MLFLOW_AUTOMATION_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install python dependencies
        run: |
          pip install requirements/lint-requirements.txt
      - name: Install JS dependencies
        working-directory: mlflow/server/js
        run: |
          npm i --only=dev
      - run: |
          black .
      - working-directory: mlflow/server/js
        run: |
          npm run lint:fix
      - working-directory: mlflow/server/js
        run: |
          npm run extract-i18n
      - name: Check diff
        id: check-diff
        run: |
          has_diff=$([[ -z "$(git diff)" ]] && echo "false" || echo "true")
          echo "::set-output name=has_diff::$has_diff"
      - name: Commit changes
        if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
        run: |
          git config --global user.name 'mlflow-automation'
          git config --global user.email 'mlflow-automation@users.noreply.github.com'
          git add -A
          run_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git commit --signoff -m "Autoformat (run URL: $run_url)"
          git push
