name: Automerge

on:
  schedule:
    - cron: "*/1 * * * *" # Run every minute

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Automerge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            const script = require('./.github/workflows/auto-merge.js');
            await script({ github, context });
