name: Automerge PRs

on:
  schedule:
    - cron: "*/10 * * * *" # Run every 10 minutes

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Automerge PRs with "automerge" label created within the last month and are mergeable
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          retries: 3
          script: |
            const script = require('./auto-merge.js')
            await script({github, context})
