name: Requirements

on:
  pull_request:
    paths:
      - requirements/core-requirements.yaml
      - requirements/skinny-requirements.yaml
  schedule:
    - cron: '0 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  MLFLOW_CONDA_HOME: /usr/share/miniconda

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  skinny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          # Best effort to test MLflow with newer versions of dependencies and increase
          # the maximum supported major versions. For example, pandas > 1.3 is not installable
          # in Python 3.7, but it is in Python 3.8.
          python-version: '3.8'
      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt
      - uses: ./.github/actions/update-requirements
        with:
          requirements-yaml-location: requirements/skinny-requirements.yaml
          requirements-txt-output-location: requirements/skinny-requirements.txt
      - name: Install dependencies
        env:
          INSTALL_SKINNY_PYTHON_DEPS: true
          MLFLOW_SKINNY: true
        run: |
          source ./dev/install-common-deps.sh
      - name: Run tests
        run: |
          ./dev/run-python-skinny-tests.sh

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: '3.8'
      - uses: ./.github/actions/setup-pyenv
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt
      - uses: ./.github/actions/update-requirements
        with:
          requirements-yaml-location: requirements/skinny-requirements.yaml
          requirements-txt-output-location: requirements/skinny-requirements.txt
      - uses: ./.github/actions/update-requirements
        with:
          requirements-yaml-location: requirements/core-requirements.yaml
          requirements-txt-output-location: requirements/core-requirements.txt
      - name: Install dependencies
        env:
          INSTALL_ML_DEPENDENCIES: true
        run: |
          source ./dev/install-common-deps.sh
      - name: Run tests
        env:
          SPARK_LOCAL_IP: 127.0.0.1
        run: |
          source dev/setup-ssh.sh
          ./dev/run-python-tests.sh

  create-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs: [skinny, core]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: '3.8'
      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt
      - uses: ./.github/actions/update-requirements
        id: skinny
        with:
          requirements-yaml-location: requirements/skinny-requirements.yaml
          requirements-txt-output-location: requirements/skinny-requirements.txt
      - uses: ./.github/actions/update-requirements
        id: core
        with:
          requirements-yaml-location: requirements/core-requirements.yaml
          requirements-txt-output-location: requirements/core-requirements.txt
      # If there are no changes, the create-pull-request action exits silently
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MLFLOW_AUTOMATION_TOKEN }}
          add-paths: requirements
          commit-message: 'Update requirements'
          signoff: true
          committer: 'mlflow-automation <mlflow-automation@users.noreply.github.com>'
          author: 'mlflow-automation <mlflow-automation@users.noreply.github.com>'
          branch: 'updated-requirements'
          branch-suffix: timestamp
          title: 'Update requirements'
          body: |
            Run URL: https://github.com/mlflow/mlflow/runs/${{ github.run_id }}
