name: Review

on:
  pull_request:
    types: [review_requested]

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'mlflow-team'}}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const author = context.payload.pull_request.user.login;
            const reviewers = [
              "B-Step62",
              "BenWilson2",
              "daniellok-db",
              "harupy",
              "serena-ruan",
              "WeichenXu123",
            ];
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers.filter((r) => r !== author),
            })
